// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tracking_service.Tracking.Infastructrure.Models;

#nullable disable

namespace tracking_service.Migrations
{
    [DbContext(typeof(FoodProductsDbContext))]
    partial class FoodProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tracking_service.Models.TrackingEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("tracking_events_pkey");

                    b.HasIndex("SessionId");

                    b.HasIndex(new[] { "EventType" }, "idx_tracking_event");

                    b.HasIndex(new[] { "ProductId" }, "idx_tracking_product");

                    b.HasIndex(new[] { "UserId" }, "idx_tracking_user");

                    b.ToTable("tracking_events", (string)null);
                });

            modelBuilder.Entity("tracking_service.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_sessions_pkey");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("tracking_service.Models.TrackingEvent", b =>
                {
                    b.HasOne("tracking_service.Models.UserSession", "Session")
                        .WithMany("TrackingEvents")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("tracking_events_session_id_fkey");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("tracking_service.Models.UserSession", b =>
                {
                    b.Navigation("TrackingEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
