CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE user_sessions (
    id uuid NOT NULL,
    user_id uuid,
    started_at timestamp without time zone DEFAULT (now()),
    CONSTRAINT user_sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE tracking_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid,
    session_id uuid,
    event_type character varying(50),
    product_id uuid,
    created_at timestamp without time zone DEFAULT (now()),
    CONSTRAINT tracking_events_pkey PRIMARY KEY (id),
    CONSTRAINT tracking_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES user_sessions (id)
);

CREATE INDEX idx_tracking_event ON tracking_events (event_type);

CREATE INDEX idx_tracking_product ON tracking_events (product_id);

CREATE INDEX idx_tracking_user ON tracking_events (user_id);

CREATE INDEX "IX_tracking_events_session_id" ON tracking_events (session_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260316034053_v1', '8.0.23');

COMMIT;

